apiVersion: v1
kind: ConfigMap
metadata:
  name: jobs-app-config
  namespace: video-processor
data:
  LOG_LEVEL: "INFO"
  PYTHONUNBUFFERED: "1"
  DATABASE_URL: "postgresql+asyncpg://postgres:postgres123@postgres-job:5432/job_db"
  REDIS_URL: "redis://redis:6379/2"
  AWS_ENDPOINT_URL: "http://localstack:4566"
  AWS_DEFAULT_REGION: "us-east-1"
  S3_INPUT_BUCKET: "video-uploads"
  S3_OUTPUT_BUCKET: "video-outputs"
  SQS_QUEUE_URL: "http://localstack:4566/000000000000/job-queue"
  SQS_JOB_QUEUE_URL: "http://localstack:4566/000000000000/job-queue"
  SNS_TOPIC_ARN: "arn:aws:sns:us-east-1:000000000000:job-events"
  AUTH_SERVICE_URL: "http://auth-service:8000"
  VIDEO_SERVICE_URL: "http://video-service:8000"
