apiVersion: v1
kind: Service
metadata:
  name: job-api-service
  namespace: video-processor
spec:
  selector:
    app: job-api-service
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: http
